import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Printer, Download } from "lucide-react";
import { Disclaimer } from "@/components/disclaimer";

export const Route = createFileRoute("/_authenticated/summary")({
  head: () => ({ meta: [{ title: "Doctor summary · HealthThread" }] }),
  component: Summary,
});

type Profile = {
  full_name: string | null; date_of_birth: string | null; sex: string | null;
  blood_type: string | null; height_cm: number | null; weight_kg: number | null;
  allergies: string | null; medications: string | null; conditions: string | null;
  emergency_contact: string | null;
};

type Event = { id: string; event_date: string; event_type: string; title: string; description: string | null; provider: string | null };

function Summary() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) return;
      const [{ data: p }, { data: e }] = await Promise.all([
        supabase.from("profiles").select("*").eq("id", u.user.id).maybeSingle(),
        supabase.from("health_events").select("id, event_date, event_type, title, description, provider").order("event_date", { ascending: false }).limit(25),
      ]);
      setProfile(p as Profile | null);
      setEvents((e as Event[]) ?? []);
      setLoading(false);
    })();
  }, []);

  function download() {
    const lines: string[] = [];
    lines.push("HealthThread — Personal Medical Summary");
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push("");
    if (profile) {
      lines.push("PROFILE");
      lines.push(`Name: ${profile.full_name ?? "—"}`);
      lines.push(`DOB: ${profile.date_of_birth ?? "—"}   Sex: ${profile.sex ?? "—"}   Blood: ${profile.blood_type ?? "—"}`);
      lines.push(`Height: ${profile.height_cm ?? "—"} cm   Weight: ${profile.weight_kg ?? "—"} kg`);
      lines.push(`Allergies: ${profile.allergies ?? "—"}`);
      lines.push(`Medications: ${profile.medications ?? "—"}`);
      lines.push(`Conditions: ${profile.conditions ?? "—"}`);
      lines.push(`Emergency contact: ${profile.emergency_contact ?? "—"}`);
      lines.push("");
    }
    lines.push("RECENT EVENTS");
    events.forEach((e) => {
      lines.push(`- ${e.event_date} [${e.event_type}] ${e.title}${e.provider ? ` (${e.provider})` : ""}`);
      if (e.description) lines.push(`    ${e.description}`);
    });
    lines.push("");
    lines.push("Disclaimer: HealthThread does not diagnose, treat, or replace a licensed clinician.");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `healththread-summary-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (loading) return <p className="text-sm text-muted-foreground">Loading…</p>;

  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Doctor summary</h1>
          <p className="mt-1 text-sm text-muted-foreground">A one-page snapshot you can share with any clinician.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => window.print()}><Printer className="mr-1.5 h-4 w-4" /> Print</Button>
          <Button onClick={download}><Download className="mr-1.5 h-4 w-4" /> Download</Button>
        </div>
      </div>

      <article className="rounded-2xl border border-border bg-card p-8 shadow-card print:border-0 print:shadow-none">
        <header className="border-b border-border pb-4">
          <h2 className="text-xl font-semibold">{profile?.full_name ?? "Patient summary"}</h2>
          <p className="text-xs text-muted-foreground">Generated by HealthThread · {new Date().toLocaleDateString()}</p>
        </header>

        <section className="mt-5 grid gap-3 text-sm md:grid-cols-2">
          <Info label="Date of birth" value={profile?.date_of_birth} />
          <Info label="Sex" value={profile?.sex} />
          <Info label="Blood type" value={profile?.blood_type} />
          <Info label="Height / weight" value={[profile?.height_cm && `${profile.height_cm} cm`, profile?.weight_kg && `${profile.weight_kg} kg`].filter(Boolean).join(" · ") || null} />
          <Info label="Emergency contact" value={profile?.emergency_contact} full />
        </section>

        <section className="mt-6 space-y-3 text-sm">
          <Block label="Allergies" value={profile?.allergies} />
          <Block label="Current medications" value={profile?.medications} />
          <Block label="Ongoing conditions" value={profile?.conditions} />
        </section>

        <section className="mt-8">
          <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Recent events</h3>
          {events.length === 0 ? (
            <p className="mt-2 text-sm text-muted-foreground">No events recorded yet.</p>
          ) : (
            <ul className="mt-2 space-y-2">
              {events.map((e) => (
                <li key={e.id} className="rounded-lg border border-border p-3 text-sm">
                  <div className="flex flex-wrap items-baseline gap-2">
                    <span className="font-medium">{e.title}</span>
                    <span className="text-xs text-muted-foreground">
                      {e.event_date} · {e.event_type}{e.provider ? ` · ${e.provider}` : ""}
                    </span>
                  </div>
                  {e.description ? <p className="mt-1 text-muted-foreground">{e.description}</p> : null}
                </li>
              ))}
            </ul>
          )}
        </section>

        <footer className="mt-8 border-t border-border pt-4 text-xs text-muted-foreground">
          HealthThread helps you remember, organize, and communicate your medical history. It does not
          diagnose, treat, or replace a licensed clinician.
        </footer>
      </article>

      <Disclaimer className="mt-6 print:hidden" />
    </div>
  );
}

function Info({ label, value, full }: { label: string; value?: string | null; full?: boolean }) {
  return (
    <div className={full ? "md:col-span-2" : ""}>
      <p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p>
      <p className="mt-0.5">{value || "—"}</p>
    </div>
  );
}
function Block({ label, value }: { label: string; value?: string | null }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p>
      <p className="mt-1 whitespace-pre-wrap">{value || "—"}</p>
    </div>
  );
}
