/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated.trends'
import { Route as AuthenticatedTracesRouteImport } from './routes/_authenticated.traces'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated.summary'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated.log'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated.import'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAddEventRouteImport } from './routes/_authenticated.add-event'
import { Route as AuthenticatedEditEventIdRouteImport } from './routes/_authenticated.edit-event.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTracesRoute = AuthenticatedTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddEventRoute = AuthenticatedAddEventRouteImport.update({
  id: '/add-event',
  path: '/add-event',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditEventIdRoute =
  AuthenticatedEditEventIdRouteImport.update({
    id: '/edit-event/$id',
    path: '/edit-event/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-event': typeof AuthenticatedAddEventRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/import': typeof AuthenticatedImportRoute
  '/log': typeof AuthenticatedLogRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/traces': typeof AuthenticatedTracesRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/edit-event/$id': typeof AuthenticatedEditEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-event': typeof AuthenticatedAddEventRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/import': typeof AuthenticatedImportRoute
  '/log': typeof AuthenticatedLogRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/traces': typeof AuthenticatedTracesRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/edit-event/$id': typeof AuthenticatedEditEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add-event': typeof AuthenticatedAddEventRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/traces': typeof AuthenticatedTracesRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/edit-event/$id': typeof AuthenticatedEditEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add-event'
    | '/chat'
    | '/documents'
    | '/import'
    | '/log'
    | '/onboarding'
    | '/summary'
    | '/traces'
    | '/trends'
    | '/api/transcribe'
    | '/edit-event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add-event'
    | '/chat'
    | '/documents'
    | '/import'
    | '/log'
    | '/onboarding'
    | '/summary'
    | '/traces'
    | '/trends'
    | '/api/transcribe'
    | '/edit-event/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add-event'
    | '/_authenticated/chat'
    | '/_authenticated/documents'
    | '/_authenticated/import'
    | '/_authenticated/log'
    | '/_authenticated/onboarding'
    | '/_authenticated/summary'
    | '/_authenticated/traces'
    | '/_authenticated/trends'
    | '/api/transcribe'
    | '/_authenticated/edit-event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traces': {
      id: '/_authenticated/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AuthenticatedTracesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-event': {
      id: '/_authenticated/add-event'
      path: '/add-event'
      fullPath: '/add-event'
      preLoaderRoute: typeof AuthenticatedAddEventRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-event/$id': {
      id: '/_authenticated/edit-event/$id'
      path: '/edit-event/$id'
      fullPath: '/edit-event/$id'
      preLoaderRoute: typeof AuthenticatedEditEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddEventRoute: typeof AuthenticatedAddEventRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedTracesRoute: typeof AuthenticatedTracesRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedEditEventIdRoute: typeof AuthenticatedEditEventIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddEventRoute: AuthenticatedAddEventRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedTracesRoute: AuthenticatedTracesRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedEditEventIdRoute: AuthenticatedEditEventIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
